  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module monster_hunter::monster_catch_attempt_event {

  use sui::event;

  use std::ascii::String;

  use monster_hunter::monster_type::MonsterType;

  use monster_hunter::direction::Direction;

  use monster_hunter::terrain_type::TerrainType;

  use monster_hunter::monster_catch_result::MonsterCatchResult;

  use monster_hunter::map_config::MapConfig;

  use monster_hunter::position::Position;

  use monster_hunter::monster_info::MonsterInfo;

  public struct MonsterCatchAttemptEvent has copy, drop {
    player: address,
    monster: address,
    result: MonsterCatchResult,
  }

  public fun new(player: address, monster: address, result: MonsterCatchResult): MonsterCatchAttemptEvent {
    MonsterCatchAttemptEvent {
                                   player,monster,result
                               }
  }
}
